### ISSUE TITLE
Lock Vault APRs - UI suggestion

### ISSUE THREAD

**Issue by J-n-a-k** [Popcorn-Limited/vaultcraft#213]
Before they were depreciated, the Lock Vault APRs were trailing APRs based on TVL at the time of AID distributions. This meant that with a large influx of deposits the APRs became very inaccurate — poor user experience for depositors choosing to lock capital for several months with assumptions about their returns. 

Assuming the new vaults will have the same issue, Merkl has a nice UI solution that could help. They show the total rewards allocated to each of their incentivized pools:

<img width="805" alt="Screenshot 2024-01-31 at 1 55 52 PM" src="https://github.com/Popcorn-Limited/vaultcraft/assets/155658337/a75e0bad-e359-4490-8390-844b47130be0">

So for the lock vaults, you could add for example "945 ARB / week" somewhere on the vault UI and label the APR "trailing APR" or something to add some clarity and set expectations.

joey_pop

**Comment by alec-pop** [comment]
@J-n-a-k
I think the best solution here is labeling the APR as "Trailing APR" or "Last Week APR"

The 945/ARB a week would not be accurate due to the variability of the AID distributions. There is a 2-week fixed ramp up period, but after this, it is a product of Frax's weekly budget, the TVL of all AID vaults, and their 4% target APR.

Will let you know when this is updated

**Comment by alec-pop** [comment]
Closing this ticket with 1k oVCX reward
Updates have been made to UI to explain each value on vault cards
